#! /usr/bin/env python3

import os
import shutil
import psutil

def check_reboot():
	"""Returns True if the computer has a pending reboot"""
	return os.path.exists("/run/reboot-required")


def check(disk, min_gb , min_percent):
	global disk_usagefree
	disk_usage = shutil.disk_usage(disk)
	disk_usagefree = disk_usage.free
	percent = 100 * disk_usagefree / disk_usage.total
	global current_gb
	current_gb = disk_usagefree / 2 ** 30
	if percent < min_percent or current_gb < min_gb:
		return False
	return True


def check_root_full():
	"""Returns True if the root partition is full, false otherwise"""
	return check(disk="/", min_gb=2, min_percent=10)

def main():
	if check_reboot():
		print("Pending Reboot")
		sys.exit(1)
	if check():
		print("Root partition full")
		sys.exit(1)

	print("Everything ok")
	sys.exit(0)
def cpu():
	global usage
	usage = psutil.cpu_percent(1)
	return usage < 75

if not check("/" , 2 , 20) or not cpu():
	print("ERROR Insufficient current disk space!")
else:
	print("{} or {}  \n{} \nEverything ok!".format(disk_usagefree ,current_gb , usage ))


