#! /usr/bin/env python3

import os
import shutil
import psutil
import sys
import socket

def check_reboot():
	"""Returns True if the computer has a pending reboot"""
	return os.path.exists("/run/reboot-required")


def check(disk, min_gb , min_percent):
	global disk_usagefree
	disk_usage = shutil.disk_usage(disk)
	disk_usagefree = disk_usage.free
	percent = 100 * disk_usagefree / disk_usage.total
	global current_gb
	current_gb = disk_usagefree / 2 ** 30
	if percent < min_percent or current_gb < min_gb:
		return True
	return False


def check_no_network():
	"""Returns True if it fails to resolve Google's URL, False if otherwise"""
	try:
		socket.gethostbyname("www.google.com")
		return False
	except:
		return True

def check_root_full():
	"""Returns True if the root partition is full, false otherwise"""
	return check(disk="/", min_gb=2, min_percent=10)


def cpu():
	usage = psutil.cpu_percent(1)
	if usage > 75:
		return True
	return False

def disk_space():
	if not check("/" , 2 , 10) or not cpu():
		return False
	else:
		return True

def main():
	checks = [(check_reboot, "Pending Reboot"), (check_root_full, "Root partition is full"), (cpu, "Insufficient CPU"), (disk_space, "Insufficient Disk Space"), (check_no_network, "No Working Network")]
	everything_ok = True
	for check,msg in checks:
		if check():
			print(msg)
			everything_ok = False
	if not everything_ok:
		sys.exit(1)

	print("Everything ok")
	sys.exit(0)
main()
